language: node_js # Sets which engine use to build the project
node_js: "node" # Specifies node version to use "node"="latest"
install: npm install
services: mongodb
cache: # Caching Node Modules :D
  directories:
    - "node_modules"
script:
    - npm run start